# Generated by Django 4.1.7 on 2023-06-11 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation date"
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="Market")),
                ("open_price", models.FloatField(verbose_name="open_price")),
                ("high_price", models.FloatField(verbose_name="high_price")),
                ("low_price", models.FloatField(verbose_name="low_price")),
                ("variation", models.FloatField(verbose_name="variation")),
            ],
        ),
    ]
